config/routes.rb
Rails.application.routes.draw do

  
  
  resources :invoices, path: 'backend/invoices' do
    resources :invoice_items, path: 'backend/invoice_items'
  end
  
  
  devise_for :clients, path: 'client_auth'
  devise_for :employees, path: 'employee_auth'

  get 'costumers', controller: :costumers, action: :home, alias: 'costumers'
  get 'eventos', controller: :costumers, action: :eventos, alias: 'eventos'
  get 'locales', controller: :costumers, action: :locales, alias: 'locales'
  get 'contacto', controller: :costumers, action: :contacto, alias: 'contacto'
  get 'reservas', controller: :costumers, action: :reservas, alias: 'reservas'
  get 'pedidos', controller: :costumers, action: :pedidos, alias: 'pedidos'
  get 'canciones', controller: :costumers, action: :canciones, alias: 'canciones'
  get 'comentar', controller: :costumers, action: :comentar, alias: 'comentar'
  get 'reservas/:id/cancelar', controller: :costumers, action: :cancel_reservation, as: :cancel_reservation
  get 'pedidos/:id/cancelar', controller: :costumers, action: :cancel_order, as: :cancel_order
  get 'canciones/:id/cancelar', controller: :costumers, action: :cancel_song, as: :cancel_song
  match '/costumers/add_reservation', to: 'costumers#add_reservation', via: 'post'
  match '/costumers/add_order', to: 'costumers#add_order', via: 'post'
  match '/costumers/add_song', to: 'costumers#add_song', via: 'post'
  match '/costumers/add_comment', to: 'costumers#add_comment', via: 'post'

  resources :products, path: 'backend/products'
  resources :orders, path: 'backend/orders'
  resources :reservations, path: 'backend/reservations'
  resources :events, path: 'backend/events'
  resources :categories, path: 'backend/categories'
  resources :employees, path: 'backend/employees'
  resources :employee_roles, path: 'backend/employee_roles'
  resources :songs, path: 'backend/songs'
  resources :genres, path: 'backend/genres'
  resources :singers, path: 'backend/singers'
  resources :rooms, path: 'backend/rooms'
  resources :clients, path: 'backend/clients'
  resources :shops, path: 'backend/shops'
  resources :playlists, path: 'backend/playlists'
  resources :comments, path: 'backend/comments'
  get 'welcome/homepage', path: 'backend'

  
  root 'costumers#home'
  

end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id                     :integer          not null, primary key
#  nom_emp                :string(255)
#  dni                    :integer
#  phone                  :integer
#  employee_role_id       :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#

class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :employee_role
  has_many :shops

  validates :nom_emp, presence: true
  validates :dni, presence: true, uniqueness: {case_sensitive: false}
  validates :employee_role, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}

  
  def role_name
    if self.employee_role.present?
        self.employee_role.nom_rol
    end
  end

  def to_s
   self.nom_emp
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_employee!
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    
    # Eliminar parámetro password si no ha sido ingresado, para que devise no actualice o valide password si no ha sido ingresado, mantenga password actual
    if params[:employee][:password].blank?
      params[:employee].delete(:password)
      params[:employee].delete(:password_confirmation)
    end    
    
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:nom_emp, :dni, :phone, :employee_role_id, :email, :password, :current_password, :password_confirmation)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= simple_form_for @employee, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nom_emp %>
  <%= error_span(@employee[:nom_emp]) %>
  <%= f.input :dni %>
  <%= error_span(@employee[:dni]) %>
  <%= f.input :phone %>
  <%= error_span(@employee[:phone]) %>
  <%= f.association :employee_role %>   
  <%= error_span(@employee[:employee_role]) %>
  <%= f.input :email %>
  <%= error_span(@employee[:email]) %>


  <% if @employee.persisted?  %>
    <%= f.input :password, autocomplete: "off", hint: "leave it blank if you don't want to change it", required: false %>
    <%= error_span(@employee[:password]) %>
    <%= f.input :password_confirmation, required: false %>
    <%= error_span(@employee[:password_confirmation]) %>
  <% else %>
    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
    <%= error_span(@employee[:password]) %>
    <%= f.input :password_confirmation, required: true %>
    <%= error_span(@employee[:password_confirmation]) %>
  <% end %>


  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                employees_path, :class => 'btn btn-default' %>
<% end %>

app/views/employees/edit.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1>Empleados</h1>
</div>

<%= link_to t('.new', :default => "Agregar"), new_employee_path, :class => 'btn btn-primary' %>
<br>
<br>

<table id="datatable" class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nom_emp) %></th>
      <th><%= model_class.human_attribute_name(:dni) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:employee_role_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to employee.id, employee_path(employee) %></td>
        <td><%= employee.nom_emp %></td>
        <td><%= employee.dni %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.role_name %></td>
        <td><%=l employee.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_path(employee), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      employee_path(employee),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/show.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nom_emp) %>:</strong></dt>
  <dd><%= @employee.nom_emp %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dni) %>:</strong></dt>
  <dd><%= @employee.dni %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @employee.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:employee_role_id) %>:</strong></dt>
  <dd><%= @employee.role_name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              employees_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_employee_path(@employee), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              employee_path(@employee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>