config/routes.rb
Rails.application.routes.draw do

  
  
  resources :invoices, path: 'backend/invoices' do
    resources :invoice_items, path: 'backend/invoice_items'
  end
  
  
  devise_for :clients, path: 'client_auth'
  devise_for :employees, path: 'employee_auth'

  get 'costumers', controller: :costumers, action: :home, alias: 'costumers'
  get 'eventos', controller: :costumers, action: :eventos, alias: 'eventos'
  get 'locales', controller: :costumers, action: :locales, alias: 'locales'
  get 'contacto', controller: :costumers, action: :contacto, alias: 'contacto'
  get 'reservas', controller: :costumers, action: :reservas, alias: 'reservas'
  get 'pedidos', controller: :costumers, action: :pedidos, alias: 'pedidos'
  get 'canciones', controller: :costumers, action: :canciones, alias: 'canciones'
  get 'comentar', controller: :costumers, action: :comentar, alias: 'comentar'
  get 'reservas/:id/cancelar', controller: :costumers, action: :cancel_reservation, as: :cancel_reservation
  get 'pedidos/:id/cancelar', controller: :costumers, action: :cancel_order, as: :cancel_order
  get 'canciones/:id/cancelar', controller: :costumers, action: :cancel_song, as: :cancel_song
  match '/costumers/add_reservation', to: 'costumers#add_reservation', via: 'post'
  match '/costumers/add_order', to: 'costumers#add_order', via: 'post'
  match '/costumers/add_song', to: 'costumers#add_song', via: 'post'
  match '/costumers/add_comment', to: 'costumers#add_comment', via: 'post'

  resources :products, path: 'backend/products'
  resources :orders, path: 'backend/orders'
  resources :reservations, path: 'backend/reservations'
  resources :events, path: 'backend/events'
  resources :categories, path: 'backend/categories'
  resources :employees, path: 'backend/employees'
  resources :employee_roles, path: 'backend/employee_roles'
  resources :songs, path: 'backend/songs'
  resources :genres, path: 'backend/genres'
  resources :singers, path: 'backend/singers'
  resources :rooms, path: 'backend/rooms'
  resources :clients, path: 'backend/clients'
  resources :shops, path: 'backend/shops'
  resources :playlists, path: 'backend/playlists'
  resources :comments, path: 'backend/comments'
  get 'welcome/homepage', path: 'backend'

  
  root 'costumers#home'
  

end

app/models/shop.rb
# == Schema Information
#
# Table name: shops
#
#  id          :integer          not null, primary key
#  code        :string(255)
#  name        :string(255)
#  address     :string(255)
#  telephone   :string(255)
#  email       :string(255)
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  employee_id :integer
#

class Shop < ActiveRecord::Base
    belongs_to :employee
    has_many :rooms
    has_many :reservations
    accepts_nested_attributes_for :rooms
    validates :code, :name, :address, :telephone, :email, :employee_id, presence: true
    validates :code, uniqueness: true
    validates :telephone, numericality: { only_integer: true }
    validates :code, length: { maximum: 3 }
    validates :telephone, :name, length: { maximum: 10 }
    validates :description, length: { maximum: 100 }
    validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }
    
    def admin_name
        if self.employee.present?
            self.employee.nom_emp
        end
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_employee!
  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:code, :name, :address, :telephone, :email, :description, :employee_id)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= simple_form_for @shop, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :code %>
  <%= error_span(@shop[:code]) %>
  <%= f.input :name %>
  <%= error_span(@shop[:name]) %>
  <%= f.input :address %>
  <%= error_span(@shop[:address]) %>
  <%= f.input :telephone %>
  <%= error_span(@shop[:telephone]) %>
  <%= f.input :email %>
  <%= error_span(@shop[:email]) %>
  <%= f.input :description %>
  <%= error_span(@shop[:description]) %>
  <%= f.association :employee %> 
  <%= error_span(@shop[:employee]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                shops_path, :class => 'btn btn-default' %>
<% end %>

app/views/shops/edit.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/index.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1>Locales</h1>
</div>

<%= link_to t('.new', :default => "Agregar"), new_shop_path, :class => 'btn btn-primary' %>
<br>
<br>

<table id="datatable" class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:telephone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th>Administrador</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= link_to shop.id, shop_path(shop) %></td>
        <td><%= shop.code %></td>
        <td><%= shop.name %></td>
        <td><%= shop.address %></td>
        <td><%= shop.telephone %></td>
        <td><%= shop.email %></td>
        <td><%= shop.description %></td>
        <td><%= shop.admin_name %></td>
        <td><%=l shop.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_shop_path(shop), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      shop_path(shop),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shops/new.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/shops/show.html.erb
<%- model_class = Shop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @shop.code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @shop.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @shop.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telephone) %>:</strong></dt>
  <dd><%= @shop.telephone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @shop.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @shop.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:admin) %>:</strong></dt>
  <dd><%= @shop.admin_name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              shops_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_shop_path(@shop), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              shop_path(@shop),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>