config/routes.rb
Rails.application.routes.draw do

  
  
  resources :invoices, path: 'backend/invoices' do
    resources :invoice_items, path: 'backend/invoice_items'
  end
  
  
  devise_for :clients, path: 'client_auth'
  devise_for :employees, path: 'employee_auth'

  get 'costumers', controller: :costumers, action: :home, alias: 'costumers'
  get 'eventos', controller: :costumers, action: :eventos, alias: 'eventos'
  get 'locales', controller: :costumers, action: :locales, alias: 'locales'
  get 'contacto', controller: :costumers, action: :contacto, alias: 'contacto'
  get 'reservas', controller: :costumers, action: :reservas, alias: 'reservas'
  get 'pedidos', controller: :costumers, action: :pedidos, alias: 'pedidos'
  get 'canciones', controller: :costumers, action: :canciones, alias: 'canciones'
  get 'comentar', controller: :costumers, action: :comentar, alias: 'comentar'
  get 'reservas/:id/cancelar', controller: :costumers, action: :cancel_reservation, as: :cancel_reservation
  get 'pedidos/:id/cancelar', controller: :costumers, action: :cancel_order, as: :cancel_order
  get 'canciones/:id/cancelar', controller: :costumers, action: :cancel_song, as: :cancel_song
  match '/costumers/add_reservation', to: 'costumers#add_reservation', via: 'post'
  match '/costumers/add_order', to: 'costumers#add_order', via: 'post'
  match '/costumers/add_song', to: 'costumers#add_song', via: 'post'
  match '/costumers/add_comment', to: 'costumers#add_comment', via: 'post'

  resources :products, path: 'backend/products'
  resources :orders, path: 'backend/orders'
  resources :reservations, path: 'backend/reservations'
  resources :events, path: 'backend/events'
  resources :categories, path: 'backend/categories'
  resources :employees, path: 'backend/employees'
  resources :employee_roles, path: 'backend/employee_roles'
  resources :songs, path: 'backend/songs'
  resources :genres, path: 'backend/genres'
  resources :singers, path: 'backend/singers'
  resources :rooms, path: 'backend/rooms'
  resources :clients, path: 'backend/clients'
  resources :shops, path: 'backend/shops'
  resources :playlists, path: 'backend/playlists'
  resources :comments, path: 'backend/comments'
  get 'welcome/homepage', path: 'backend'

  
  root 'costumers#home'
  

end

app/models/employee_role.rb
# == Schema Information
#
# Table name: employee_roles
#
#  id         :integer          not null, primary key
#  nom_rol    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class EmployeeRole < ActiveRecord::Base
    has_many :employees
    validates :nom_rol, presence: true
    def to_s
     self.nom_rol
    end

end

app/controllers/employee_roles_controller.rb
class EmployeeRolesController < ApplicationController
  before_filter :authenticate_employee!
  before_action :set_employee_role, only: [:show, :edit, :update, :destroy]

  # GET /employee_roles
  # GET /employee_roles.json
  def index
    @employee_roles = EmployeeRole.all
  end

  # GET /employee_roles/1
  # GET /employee_roles/1.json
  def show
  end

  # GET /employee_roles/new
  def new
    @employee_role = EmployeeRole.new
  end

  # GET /employee_roles/1/edit
  def edit
  end

  # POST /employee_roles
  # POST /employee_roles.json
  def create
    @employee_role = EmployeeRole.new(employee_role_params)

    respond_to do |format|
      if @employee_role.save
        format.html { redirect_to @employee_role, notice: 'Employee role was successfully created.' }
        format.json { render :show, status: :created, location: @employee_role }
      else
        format.html { render :new }
        format.json { render json: @employee_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_roles/1
  # PATCH/PUT /employee_roles/1.json
  def update
    respond_to do |format|
      if @employee_role.update(employee_role_params)
        format.html { redirect_to @employee_role, notice: 'Employee role was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_role }
      else
        format.html { render :edit }
        format.json { render json: @employee_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_roles/1
  # DELETE /employee_roles/1.json
  def destroy
    @employee_role.destroy
    respond_to do |format|
      format.html { redirect_to employee_roles_url, notice: 'Employee role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_role
      @employee_role = EmployeeRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_role_params
      params.require(:employee_role).permit(:nom_rol)
    end
end

app/helpers/employee_roles_helper.rb
module EmployeeRolesHelper
end

app/views/employee_roles/_form.html.erb
<%= simple_form_for @employee_role, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nom_rol %>
  <%= error_span(@employee_role[:nom_rol]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                employee_roles_path, :class => 'btn btn-default' %>
<% end %>

app/views/employee_roles/edit.html.erb
<%- model_class = EmployeeRole -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employee_roles/index.html.erb
<%- model_class = EmployeeRole -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nom_rol) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employee_roles.each do |employee_role| %>
      <tr>
        <td><%= link_to employee_role.id, employee_role_path(employee_role) %></td>
        <td><%= employee_role.nom_rol %></td>
        <td><%=l employee_role.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employee_role_path(employee_role), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      employee_role_path(employee_role),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_employee_role_path,
            :class => 'btn btn-primary' %>

app/views/employee_roles/new.html.erb
<%- model_class = EmployeeRole -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employee_roles/show.html.erb
<%- model_class = EmployeeRole -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nom_rol) %>:</strong></dt>
  <dd><%= @employee_role.nom_rol %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              employee_roles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_employee_role_path(@employee_role), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              employee_role_path(@employee_role),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>