config/routes.rb
Rails.application.routes.draw do

  
  
  resources :invoices, path: 'backend/invoices' do
    resources :invoice_items, path: 'backend/invoice_items'
  end
  
  
  devise_for :clients, path: 'client_auth'
  devise_for :employees, path: 'employee_auth'

  get 'costumers', controller: :costumers, action: :home, alias: 'costumers'
  get 'eventos', controller: :costumers, action: :eventos, alias: 'eventos'
  get 'locales', controller: :costumers, action: :locales, alias: 'locales'
  get 'contacto', controller: :costumers, action: :contacto, alias: 'contacto'
  get 'reservas', controller: :costumers, action: :reservas, alias: 'reservas'
  get 'pedidos', controller: :costumers, action: :pedidos, alias: 'pedidos'
  get 'canciones', controller: :costumers, action: :canciones, alias: 'canciones'
  get 'comentar', controller: :costumers, action: :comentar, alias: 'comentar'
  get 'reservas/:id/cancelar', controller: :costumers, action: :cancel_reservation, as: :cancel_reservation
  get 'pedidos/:id/cancelar', controller: :costumers, action: :cancel_order, as: :cancel_order
  get 'canciones/:id/cancelar', controller: :costumers, action: :cancel_song, as: :cancel_song
  match '/costumers/add_reservation', to: 'costumers#add_reservation', via: 'post'
  match '/costumers/add_order', to: 'costumers#add_order', via: 'post'
  match '/costumers/add_song', to: 'costumers#add_song', via: 'post'
  match '/costumers/add_comment', to: 'costumers#add_comment', via: 'post'

  resources :products, path: 'backend/products'
  resources :orders, path: 'backend/orders'
  resources :reservations, path: 'backend/reservations'
  resources :events, path: 'backend/events'
  resources :categories, path: 'backend/categories'
  resources :employees, path: 'backend/employees'
  resources :employee_roles, path: 'backend/employee_roles'
  resources :songs, path: 'backend/songs'
  resources :genres, path: 'backend/genres'
  resources :singers, path: 'backend/singers'
  resources :rooms, path: 'backend/rooms'
  resources :clients, path: 'backend/clients'
  resources :shops, path: 'backend/shops'
  resources :playlists, path: 'backend/playlists'
  resources :comments, path: 'backend/comments'
  get 'welcome/homepage', path: 'backend'

  
  root 'costumers#home'
  

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
    has_many :products
    
    validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_employee!

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name, label: 'Nombre Categoría' %>
  <%= error_span(@category[:name]) %>

  <%= f.button :submit, 'Grabar', :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn btn-default' %>
<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1>Editar Categoría</h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1>Categorías de Producto</h1>
</div>
<%= link_to 'Agregar Categoría', new_category_path, :class => 'btn btn-primary' %>
<br>
<br>
<table id='datatable' class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%= category.name %></td>
        <td><%=l category.created_at %></td>
        <td>
          <%= link_to 'Editar', edit_category_path(category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("Eliminar")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => '¿Estás seguro?' },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1>Nueva Categoría</h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>